# Generated by Django 3.2.6 on 2021-09-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='نام دامنه')),
                ('price', models.IntegerField(max_length=50, null=True, verbose_name='قیمت')),
            ],
        ),
    ]
